const database = [
    {"Case":"Fasteners and Inserts","Part":"10mm Screws","Layer":1,"Location":"G4","Image":"Part Images/10mmScrews.png"},
    {"Case":"Fasteners and Inserts","Part":"15mm Screws","Layer":1,"Location":"A5,B5","Image":"Part Images/15mmScrews.png"},
    {"Case":"Fasteners and Inserts","Part":"20mm Screws","Layer":1,"Location":"H4","Image":"Part Images/20mmScrews.png"},
    {"Case":"Fasteners and Inserts","Part":"30mm Screws","Layer":1,"Location":"C5,D5","Image":"Part Images/30mmScrews.png"},
    {"Case":"Fasteners and Inserts","Part":"35mm Screws","Layer":1,"Location":"E5","Image":"Part Images/35mmScrews.png"},
    {"Case":"Fasteners and Inserts","Part":"Allen Keys","Layer":1,"Location":"F5","Image":"Part Images/AllenKeys.png"},
    {"Case":"Fasteners and Inserts","Part":"Ball Sockets","Layer":1,"Location":"H5","Image":"Part Images/BallSockets.png"},
    {"Case":"Fasteners and Inserts","Part":"Bearings","Layer":1,"Location":"I5","Image":"Part Images/Bearings.png"},
    {"Case":"Fasteners and Inserts","Part":"EZ Connect","Layer":1,"Location":"H3","Image":"Part Images/EZConnect.png"},
    {"Case":"Fasteners and Inserts","Part":"Grub Screws","Layer":1,"Location":"F4","Image":"Part Images/GrubScrews.png"},
    {"Case":"Fasteners and Inserts","Part":"IKEA","Layer":1,"Location":"F5","Image":"Part Images/IKEA.png"},
    {"Case":"Fasteners and Inserts","Part":"M3 10mm","Layer":1,"Location":"B1","Image":"Part Images/M310mm.png"},
    {"Case":"Fasteners and Inserts","Part":"M3 20mm","Layer":1,"Location":"C1","Image":"Part Images/M320mm.png"},
    {"Case":"Fasteners and Inserts","Part":"M3 30mm","Layer":1,"Location":"D1","Image":"Part Images/M330mm.png"},
    {"Case":"Fasteners and Inserts","Part":"M3 5mm","Layer":1,"Location":"A1","Image":"Part Images/M35mm.png"},
    {"Case":"Fasteners and Inserts","Part":"M3 Inserts","Layer":1,"Location":"G1","Image":"Part Images/M3Inserts.png"},
    {"Case":"Fasteners and Inserts","Part":"M3 Locknut","Layer":1,"Location":"E1","Image":"Part Images/M3Locknut.png"},
    {"Case":"Fasteners and Inserts","Part":"M3 Nut","Layer":1,"Location":"D1","Image":"Part Images/M3Nut.png"},
    {"Case":"Fasteners and Inserts","Part":"M3 Washer","Layer":1,"Location":"E1","Image":"Part Images/M3Washer.png"},
    {"Case":"Fasteners and Inserts","Part":"M3 Wingnut","Layer":1,"Location":"F1","Image":"Part Images/M3Wingnut.png"},
    {"Case":"Fasteners and Inserts","Part":"M4 10mm","Layer":1,"Location":"A2","Image":"Part Images/M410mm.png"},
    {"Case":"Fasteners and Inserts","Part":"M4 14mm","Layer":1,"Location":"B2","Image":"Part Images/M414mm.png"},
    {"Case":"Fasteners and Inserts","Part":"M4 20mm","Layer":1,"Location":"C2","Image":"Part Images/M420mm.png"},
    {"Case":"Fasteners and Inserts","Part":"M4 25mm","Layer":1,"Location":"D2","Image":"Part Images/M425mm.png"},
    {"Case":"Fasteners and Inserts","Part":"M4 Inserts","Layer":1,"Location":"G2","Image":"Part Images/M4Inserts.png"},
    {"Case":"Fasteners and Inserts","Part":"M4 Locknut","Layer":1,"Location":"H2","Image":"Part Images/M4Locknut.png"},
    {"Case":"Fasteners and Inserts","Part":"M4 Nut","Layer":1,"Location":"E2","Image":"Part Images/M4Nut.png"},
    {"Case":"Fasteners and Inserts","Part":"M4 Washer","Layer":1,"Location":"F2","Image":"Part Images/M4Washer.png"},
    {"Case":"Fasteners and Inserts","Part":"M5 20mm","Layer":1,"Location":"I2","Image":"Part Images/M520mm.png"},
    {"Case":"Fasteners and Inserts","Part":"M5 30mm","Layer":1,"Location":"A3","Image":"Part Images/M530mm.png"},
    {"Case":"Fasteners and Inserts","Part":"M5 Nut","Layer":1,"Location":"C3","Image":"Part Images/M5Nut.png"},
    {"Case":"Fasteners and Inserts","Part":"M5 Washer","Layer":1,"Location":"B3","Image":"Part Images/M5Washer.png"},
    {"Case":"Fasteners and Inserts","Part":"M5 Wingnut","Layer":1,"Location":"D3","Image":"Part Images/M5Wingnut.png"},
    {"Case":"Fasteners and Inserts","Part":"M6 30mm","Layer":1,"Location":"E3","Image":"Part Images/M630mm.png"},
    {"Case":"Fasteners and Inserts","Part":"M6 35mm","Layer":1,"Location":"F3,G3","Image":"Part Images/M635mm.png"},
    {"Case":"Fasteners and Inserts","Part":"M6 60+ mm","Layer":1,"Location":"I3","Image":"Part Images/M660+mm.png"},
    {"Case":"Fasteners and Inserts","Part":"M6 Nut","Layer":1,"Location":"A4","Image":"Part Images/M6Nut.png"},
    {"Case":"Fasteners and Inserts","Part":"M6 Washer","Layer":1,"Location":"B4","Image":"Part Images/M6Washer.png"},
    {"Case":"Fasteners and Inserts","Part":"M8 Misc","Layer":1,"Location":"C4","Image":"Part Images/M8Misc.png"},
    {"Case":"Fasteners and Inserts","Part":"Metal Taps","Layer":1,"Location":"G5","Image":"Part Images/MetalTaps.png"},
    {"Case":"Fasteners and Inserts","Part":"Nails","Layer":1,"Location":"D4","Image":"Part Images/Nails.png"},
    {"Case":"Fasteners and Inserts","Part":"Pc Screws etc","Layer":1,"Location":"E4","Image":"Part Images/PcScrewsetc.png"},
    {"Case":"Fasteners and Inserts","Part":"Universal Joint","Layer":1,"Location":"E5","Image":"Part Images/UniversalJoint.png"},
    {"Case":"Fasteners and Inserts","Part":"Wire Ferrules","Layer":1,"Location":"I4","Image":"Part Images/WireFerrules.png"},
    {"Case":"Fasteners and Inserts","Part":"25mm Screws","Layer":2,"Location":"F4","Image":"Part Images/25mmScrews.png"},
    {"Case":"Fasteners and Inserts","Part":"5mm Screws","Layer":2,"Location":"E4","Image":"Part Images/5mmScrews.png"},
    {"Case":"Fasteners and Inserts","Part":"Drill Bits","Layer":2,"Location":"B5,C5","Image":"Part Images/DrillBits.png"},
    {"Case":"Fasteners and Inserts","Part":"M3 15mm","Layer":2,"Location":"B1","Image":"Part Images/M315mm.png"},
    {"Case":"Fasteners and Inserts","Part":"M3 25mm","Layer":2,"Location":"C1","Image":"Part Images/M325mm.png"},
    {"Case":"Fasteners and Inserts","Part":"M3 45+mm","Layer":2,"Location":"D1","Image":"Part Images/M345+mm.png"},
    {"Case":"Fasteners and Inserts","Part":"M3 8mm","Layer":2,"Location":"A1","Image":"Part Images/M38mm.png"},
    {"Case":"Fasteners and Inserts","Part":"M3 Threads","Layer":2,"Location":"E1","Image":"Part Images/M3Threads.png"},
    {"Case":"Fasteners and Inserts","Part":"M4 12mm","Layer":2,"Location":"A2","Image":"Part Images/M412mm.png"},
    {"Case":"Fasteners and Inserts","Part":"M4 16mm","Layer":2,"Location":"B2","Image":"Part Images/M416mm.png"},
    {"Case":"Fasteners and Inserts","Part":"M4 30mm","Layer":2,"Location":"D2","Image":"Part Images/M430mm.png"},
    {"Case":"Fasteners and Inserts","Part":"M4 45+mm","Layer":2,"Location":"E2,F2","Image":"Part Images/M445+mm.png"},
    {"Case":"Fasteners and Inserts","Part":"M4 Wingnut","Layer":2,"Location":"E2","Image":"Part Images/M4Wingnut.png"},
    {"Case":"Fasteners and Inserts","Part":"M5 25mm","Layer":2,"Location":"A3","Image":"Part Images/M525mm.png"},
    {"Case":"Fasteners and Inserts","Part":"M5 40+mm","Layer":2,"Location":"B3,C3","Image":"Part Images/M540+mm.png"},
    {"Case":"Fasteners and Inserts","Part":"M5 8mm","Layer":2,"Location":"G2","Image":"Part Images/M58mm.png"},
    {"Case":"Fasteners and Inserts","Part":"M6 20mm","Layer":2,"Location":"E3","Image":"Part Images/M620mm.png"},
    {"Case":"Fasteners and Inserts","Part":"M6 45mm","Layer":2,"Location":"E3","Image":"Part Images/M645mm.png"},
    {"Case":"Fasteners and Inserts","Part":"M6 Locknut","Layer":2,"Location":"A4","Image":"Part Images/M6Locknut.png"},
    {"Case":"Fasteners and Inserts","Part":"M6 Wingnut","Layer":2,"Location":"B4","Image":"Part Images/M6Wingnut.png"},
    {"Case":"Fasteners and Inserts","Part":"Micro Screws","Layer":2,"Location":"D4","Image":"Part Images/MicroScrews.png"},
    {"Case":"Fasteners and Inserts","Part":"Misc Imperial","Layer":2,"Location":"A5","Image":"Part Images/MiscImperial.png"},
    {"Case":"Fasteners and Inserts","Part":"Misc Washers","Layer":2,"Location":"C4","Image":"Part Images/MiscWashers.png"},
    {"Case":"Fasteners and Inserts","Part":"Screws Large","Layer":2,"Location":"A6","Image":"Part Images/ScrewsLarge.png"},
    {"Case":"Fasteners and Inserts","Part":"Shaft Collars","Layer":2,"Location":"F2","Image":"Part Images/ShaftCollars.png"},
    {"Case":"Electronics","Part":"Resistors","Layer":1,"Location":"A1, B1","Image":"Part Images/Resistors.png"},
    {"Case":"Electronics","Part":"Class J 5% Res","Layer":1,"Location":"C1","Image":"Part Images/ClassJ5%Res.png"},
    {"Case":"Electronics","Part":"Micro SD Reader","Layer":1,"Location":"D1","Image":"Part Images/MicroSDReader.png"},
    {"Case":"Electronics","Part":"Temp Switches","Layer":1,"Location":"E1","Image":"Part Images/TempSwitches.png"},
    {"Case":"Electronics","Part":"Misc Switches","Layer":1,"Location":"F1","Image":"Part Images/MiscSwitches.png"},
    {"Case":"Electronics","Part":"LEDS","Layer":1,"Location":"G1","Image":"Part Images/LEDS.png"},
    {"Case":"Electronics","Part":"Capacitors","Layer":1,"Location":"H1, I1","Image":"Part Images/Capacitors.png"},
    {"Case":"Electronics","Part":"IR Sensors","Layer":1,"Location":"A2","Image":"Part Images/IRSensors.png"},
    {"Case":"Electronics","Part":"Cherry MX","Layer":1,"Location":"B2, C2","Image":"Part Images/CherryMX.png"},
    {"Case":"Electronics","Part":"Analog to Digital","Layer":1,"Location":"D2","Image":"Part Images/AnalogtoDigital.png"},
    {"Case":"Electronics","Part":"5V Joysticks","Layer":1,"Location":"E2","Image":"Part Images/5VJoysticks.png"},
    {"Case":"Electronics","Part":"PCA9685 Boards","Layer":1,"Location":"F2, G2","Image":"Part Images/PCA9685Boards.png"},
    {"Case":"Electronics","Part":"Barrel Plugs","Layer":1,"Location":"H2","Image":"Part Images/BarrelPlugs.png"},
    {"Case":"Electronics","Part":"XT60 Connectors","Layer":1,"Location":"I2","Image":"Part Images/XT60Connectors.png"},
    {"Case":"Electronics","Part":"Wago Connectors","Layer":1,"Location":"A3","Image":"Part Images/WagoConnectors.png"},
    {"Case":"Electronics","Part":"PCB LED Yellow","Layer":1,"Location":"B3","Image":"Part Images/PCBLEDYellow.png"},
    {"Case":"Electronics","Part":"PCB LED Red","Layer":1,"Location":"C3","Image":"Part Images/PCBLEDRed.png"},
    {"Case":"Electronics","Part":"HC-05 Bluetooth","Layer":1,"Location":"D3","Image":"Part Images/HC-05Bluetooth.png"},
    {"Case":"Electronics","Part":"Misc Connectors","Layer":1,"Location":"E3","Image":"Part Images/MiscConnectors.png"},
    {"Case":"Electronics","Part":"Twist Connectors","Layer":1,"Location":"F3","Image":"Part Images/TwistConnectors.png"},
    {"Case":"Electronics","Part":"L298N Stepper Driver","Layer":1,"Location":"G3, H3","Image":"Part Images/L298NStepperDriver.png"},
    {"Case":"Electronics","Part":"TMC2088 Driver","Layer":1,"Location":"I3","Image":"Part Images/TMC2088Driver.png"},
    {"Case":"Electronics","Part":"NRF Send/Receive","Layer":1,"Location":"A4","Image":"Part Images/NRFSend/Receive.png"},
    {"Case":"Electronics","Part":"Air Pumps","Layer":1,"Location":"B4","Image":"Part Images/AirPumps.png"},
    {"Case":"Electronics","Part":"Rotary Encoder","Layer":1,"Location":"C4","Image":"Part Images/RotaryEncoder.png"},
    {"Case":"Electronics","Part":"Endstops","Layer":1,"Location":"D4","Image":"Part Images/Endstops.png"},
    {"Case":"Electronics","Part":"9G Servos","Layer":1,"Location":"E4","Image":"Part Images/9GServos.png"},
    {"Case":"Electronics","Part":"MG90S 360","Layer":1,"Location":"F4","Image":"Part Images/MG90S360.png"},
    {"Case":"Electronics","Part":"MG996R Horns","Layer":1,"Location":"G4","Image":"Part Images/MG996RHorns.png"},
    {"Case":"Electronics","Part":"MG90S 180","Layer":1,"Location":"H4, I4","Image":"Part Images/MG90S180.png"},
    {"Case":"Electronics","Part":"Step Up/Down","Layer":1,"Location":"A5","Image":"Part Images/StepUp/Down.png"},
    {"Case":"Electronics","Part":"5V Relays","Layer":1,"Location":"B5, C5","Image":"Part Images/5VRelays.png"},
    {"Case":"Electronics","Part":"12V/2A Solenoid","Layer":1,"Location":"D5","Image":"Part Images/12V/2ASolenoid.png"},
    {"Case":"Electronics","Part":"Misc Servos","Layer":1,"Location":"E5","Image":"Part Images/MiscServos.png"},
    {"Case":"Electronics","Part":"Batteries","Layer":1,"Location":"F5, G5","Image":"Part Images/Batteries.png"},
    {"Case":"Electronics","Part":"Misc Servo-Parts","Layer":1,"Location":"H5, I5","Image":"Part Images/MiscServo-Parts.png"},
    {"Case":"Electronics","Part":"3-6V Laser","Layer":1,"Location":"A6","Image":"Part Images/3-6VLaser.png"},
    {"Case":"Electronics","Part":"A4988 Drivers","Layer":1,"Location":"B6","Image":"Part Images/A4988Drivers.png"},
    {"Case":"Electronics","Part":"Audio Boards","Layer":1,"Location":"C6","Image":"Part Images/AudioBoards.png"},
    {"Case":"Electronics","Part":"3.5 Female Jack","Layer":1,"Location":"E6","Image":"Part Images/3.5FemaleJack.png"},
    {"Case":"Electronics","Part":"Guitar Jacks","Layer":1,"Location":"F6","Image":"Part Images/GuitarJacks.png"},
    {"Case":"Electronics","Part":"Heat Shrink","Layer":1,"Location":"G6, H6, I6","Image":"Part Images/HeatShrink.png"},
    {"Case":"Electronics","Part":"Pots","Layer":2,"Location":"D1","Image":"Part Images/Pots.png"},
    {"Case":"Electronics","Part":"Ceramic Capacitors","Layer":2,"Location":"E1","Image":"Part Images/CeramicCapacitors.png"},
    {"Case":"Electronics","Part":"Transistors","Layer":2,"Location":"F1","Image":"Part Images/Transistors.png"},
    {"Case":"Electronics","Part":"Diodes","Layer":2,"Location":"G1","Image":"Part Images/Diodes.png"},
    {"Case":"Electronics","Part":"5V Steppers","Layer":2,"Location":"H1, I1","Image":"Part Images/5VSteppers.png"},
    {"Case":"Electronics","Part":"9V Battery Clips","Layer":2,"Location":"D3","Image":"Part Images/9VBatteryClips.png"},
    {"Case":"Electronics","Part":"Knobs","Layer":2,"Location":"E6","Image":"Part Images/Knobs.png"}
];

const cases = [
    {"Case":"Fasteners and Inserts","Width":9,"Height":6,"CaseLayers":2},
    {"Case":"Electronics","Width":9,"Height":6,"CaseLayers":2}
];